# -*- coding: utf-8 -*-
"""PCA Iris to allow for Graphical representations of data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gQAFGOU32UmpJlO7O14JPRtiKqgEcSj
"""

from sklearn.datasets import load_iris

iris_data = load_iris()

print(iris_data['DESCR'])

iris_data['data'].shape

from sklearn.decomposition import PCA

pca = PCA()
pca.fit(iris_data['data'])

pca.explained_variance_ratio_

X_train_pca = pca.transform(iris_data['data'])

X_train_pca.shape

iris_data['target'].shape

import matplotlib.pyplot as plt

iris_data['target']

plt.scatter(X_train_pca[:50,0],X_train_pca[:50,1], color= 'green')
plt.scatter(X_train_pca[50:100,0],X_train_pca[50:100,1], color= 'blue')
plt.scatter(X_train_pca[100:,0],X_train_pca[100:,1], color= 'red')

