# -*- coding: utf-8 -*-
"""Genetic Algorithm Assignment Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ubmH-5qSbIuDuwtNu8P6RWYmGaPU5266

# Genetic Algorithm Assignment
30% of the overall grade for this module

Marks indciated in sections below are based on percentage of marks allocated for this module

In this assignment you must choose a problem, and attempt to use the Genetic Alogrithm that we developed in class to solve this problem.

## The Problem         **(~30%)**

*   Description of the problem

---

(Double click then ...)  Type Here...

---

*   Discussion of the suitablity of Genetic Algorithms

---

(Double click then ...)  Type Here...

---

*   Complexity of the problem  (Overall marks allocated based on ..)

# The problem and the cost function   **(~20%)**
"""

#  insert code in ths cell

"""# The Individual **(~30%)**


*   Chromosone
*   Crossover
*   Mutation

## Discussion and justification on the approaches taken for the above

---

(Double click then ...)  Type Here...

---
"""

# Code for individual class in here

"""## Running the algorithm  **(~10%)**

*   Parameter choices
*   Modifications (if any) to run_genetic
*   Rationale for the above

---

(Double click then ...)  Type Here...

---
"""

#  Parameter class here

# Run Genetic method here

#  Running of the algorithm with outputs here

#  If changes to params or reruns of iterations dont overwrite, create more cells and copy code down to show evolution of final solution

"""## Results and conclusions    **(~10%)**

---

(Double click then ...)  Type Here...

---
"""